name: Run Semgrep

on:
  push:
    branches:
      - main  # Trigger the action on push to main branch (can adjust to your default branch)
  pull_request:
    branches:
      - main  # Trigger the action when a pull request is made to main branch

jobs:
  semgrep:
    runs-on: ubuntu-latest  # Use a Ubuntu runner for Linux-based containers

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Ensure correct Python version (Semgrep requires it)

    - name: Install Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install semgrep  # Install Semgrep

    - name: Run Semgrep
      run: |
        semgrep --config=auto # Runs the semgrep with the default config
